export const GET_COUNT = 'GET_COUNT';
export const INC_COUNT = 'INC_COUNT';

export const GET_GUESTS = 'GET_GUESTS';
export const UPDATE_GUEST = 'UPDATE_GUEST';
export const CREATE_GUEST = 'CREATE_GUEST';
export const DELETE_GUEST = 'DELETE_GUEST';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
